name: esme2526
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

# --- ZONE UNIQUE DES DÉPENDANCES ---
dependencies:
  flutter:
    sdk: flutter

  # Icônes et UI
  cupertino_icons: ^1.0.8

  # Vidéo et Stockage (Vos anciennes libs)
  youtube_player_iframe: ^5.2.2
  hive_ce: ^2.15.1
  hive_ce_flutter: ^2.3.3

  # --- VOS NOUVEAUX AJOUTS (Pour le QR et le Serveur) ---
  qr_flutter: ^4.1.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  network_info_plus: ^5.0.1
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_ce_generator: ^1.10.0
  build_runner: ^2.10.4

flutter:
  uses-material-design: true